### PR TITLE
Test on Python 3.7 as well

### PR DESCRIPTION
**Pull request by thomwiggers**

### CODE REVIEW

**Comment by thomwiggers** [comment]
Apparently travis haven't resolved https://github.com/travis-ci/travis-ci/issues/9815 yet

**Comment by dwolfhub** [comment]
ok so it sounds like we're just waiting for travis support?

thanks!

**Comment by myartsev** [comment]
Python 3.7 is supported on Travis CI by now

**Comment by myartsev** [comment]
Apparently only supported on xenial -_-

[https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905](https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905)

**Comment by thomwiggers** [comment]
I have since deleted my fork and I don't think I can resurrect this PR. I suggest someone opens a new one.

**Comment by dwolfhub** [comment]
opened #44

**Pull request closed without merging**
