### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by brenard**
Hello,
I'm using your lib in a project that need to be translated in french, so I added stuffs to allow to use the _extract_messages_ command of _setup.py_ and I translated messages in french.

**Note :** _MO_ files could be generated by using the _compile_catalog_ command of _setup.py_ so I excluded it from sources.

### CODE REVIEW

**Comment by dwolfhub** [comment]
Thanks for the MR. I like the added configuration for generating files, but I'm not sure if I should include the french translation or any others, simply because I can't think of way of confirming those translations are legit.

Open to suggestions, but for now maybe we just merge the setup.cfg file?

**Comment by cedricfarinazzo** [comment]
Hey!

I am French and I confirm that the French translation is correct.

Hoping that you will include these translations.

Thank you for this python library.

**Comment by jwag956** [comment]
Putting the in the setup.cfg and the .pot file would be a great start. As for 'knowing' if the xlations are correct - that's why we have a global community!

However - @cedricfarinazzo I am not completely understanding how your PR actually works. You are creating messages with the domain == "zxcvbn" - which is great - however from looking at the code - zxcvbn currently uses the global gettext rather than class level - so the only way (as I understand it) to get xlations is to change the global domain from 'messages' to 'zxcvbn' which is not a good idea. This: https://docs.python.org/3/library/gettext.html#localizing-your-application gives some ideas on how to localize a module rather than an entire application.

If I am missing something - please add a comment as to how you configured your application to use these translations... Thanks!

**Comment by dwolfhub** [comment]
Closing this one until we get an update from @cedricfarinazzo

**Pull request closed without merging**
