### PR TITLE
Support universal wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
Will need to be uploaded with `python setup.py bdist_wheel register upload`

**Comment by dwolfhub** [comment]
it's a good idea. can you see why travis might be failing for 2.7? not ready to drop support for 2.7 just yet.

**Comment by graingert** [comment]
@dwolfhub because of some accidental spacing in the `.ini` file which Python 3 ignores. Woops!

**Comment by graingert** [comment]
Seems all of the tests end like:

`/home/travis/.travis/job_stages: line 169:  2615 Terminated              travis_jigger $! $timeout $cmd`

**Pull request merged**
