### PR TITLE
Prefer stdin for password if it is readable

### PR DESCRIPTION
**Pull request by whwright**
Issue: https://github.com/dwolfhub/zxcvbn-python/issues/42

Testing:

```
↪ zxcvbn | jq
Password:
{
  "crack_times_seconds": {
    "online_no_throttling_10_per_second": "2203404010000000",
    "online_throttling_100_per_hour": "793225443600000044.0328575602",
    "offline_fast_hashing_1e10_per_second": "2203404.01",
    "offline_slow_hashing_1e4_per_second": "2203404010000"
  },
  "guesses": "22034040100000000",
  "feedback": {
    "warning": "",
    "suggestions": []
  },
  "guesses_log10": 16.343094135474317,
  "sequence": [
    {
      "guesses": 4760,
      "guesses_log10": 3.677606952720493,
      "l33t_variations": 1,
      "reversed": false,
      "rank": 4760,
      "uppercase_variations": 1,
      "dictionary_name": "us_tv_and_film",
      "matched_word": "typing",
      "base_guesses": 4760,
      "i": 0,
      "pattern": "dictionary",
      "j": 5,
      "l33t": false,
      "token": "typing"
    },
    {
      "guesses": 100000000,
      "guesses_log10": 8,
      "i": 6,
      "pattern": "bruteforce",
      "j": 13,
      "token": " in the "
    },
    {
      "guesses": 7715,
      "guesses_log10": 3.887335930399167,
      "l33t_variations": 1,
      "reversed": false,
      "rank": 7715,
      "uppercase_variations": 1,
      "dictionary_name": "us_tv_and_film",
      "matched_word": "prompt",
      "base_guesses": 7715,
      "i": 14,
      "pattern": "dictionary",
      "j": 19,
      "l33t": false,
      "token": "prompt"
    }
  ],
  "crack_times_display": {
    "online_throttling_100_per_hour": "centuries",
    "online_no_throttling_10_per_second": "centuries",
    "offline_fast_hashing_1e10_per_second": "26.0 days",
    "offline_slow_hashing_1e4_per_second": "centuries"
  },
  "score": 4,
  "password": "typing in the prompt",
  "calc_time": "0:00:00.031801"
}


↪ echo "using stdin" | zxcvbn | jq
{
  "crack_times_seconds": {
    "online_no_throttling_10_per_second": "22823200",
    "online_throttling_100_per_hour": "8216352000.000000456099158441",
    "offline_fast_hashing_1e10_per_second": "0.0228232",
    "offline_slow_hashing_1e4_per_second": "22823.2"
  },
  "guesses": "228232000",
  "feedback": {
    "warning": "",
    "suggestions": []
  },
  "guesses_log10": 8.358376536002918,
  "sequence": [
    {
      "guesses": 274,
      "guesses_log10": 2.437750562820388,
      "l33t_variations": 1,
      "reversed": false,
      "rank": 274,
      "uppercase_variations": 1,
      "dictionary_name": "english_wikipedia",
      "matched_word": "using",
      "base_guesses": 274,
      "i": 0,
      "pattern": "dictionary",
      "j": 4,
      "l33t": false,
      "token": "using"
    },
    {
      "guesses": 1000,
      "guesses_log10": 2.9999999999999996,
      "i": 5,
      "pattern": "bruteforce",
      "j": 7,
      "token": " st"
    },
    {
      "guesses": 78,
      "guesses_log10": 1.8920946026904801,
      "i": 8,
      "pattern": "sequence",
      "sequence_name": "lower",
      "j": 10,
      "sequence_space": 26,
      "ascending": true,
      "token": "din"
    }
  ],
  "crack_times_display": {
    "online_throttling_100_per_hour": "centuries",
    "online_no_throttling_10_per_second": "9.0 months",
    "offline_fast_hashing_1e10_per_second": "less than a second",
    "offline_slow_hashing_1e4_per_second": "6.0 hours"
  },
  "score": 3,
  "password": "using stdin",
  "calc_time": "0:00:00.002934"
}

↪ echo "using stdin with trailing spaces    " | zxcvbn | jq
{
  "crack_times_seconds": {
    "online_no_throttling_10_per_second": "180562883550400000000000000",
    "online_throttling_100_per_hour": "6.500263807814400360837127279E+28",
    "offline_fast_hashing_1e10_per_second": "180562883550400000",
    "offline_slow_hashing_1e4_per_second": "180562883550400000000000"
  },
  "guesses": "1805628835504000000000000000",
  "feedback": {
    "warning": "",
    "suggestions": []
  },
  "guesses_log10": 27.256628481714515,
  "sequence": [
    {
      "guesses": 274,
      "guesses_log10": 2.437750562820388,
      "l33t_variations": 1,
      "reversed": false,
      "rank": 274,
      "uppercase_variations": 1,
      "dictionary_name": "english_wikipedia",
      "matched_word": "using",
      "base_guesses": 274,
      "i": 0,
      "pattern": "dictionary",
      "j": 4,
      "l33t": false,
      "token": "using"
    },
    {
      "guesses": 1000000000000,
      "guesses_log10": 11.999999999999998,
      "i": 5,
      "pattern": "bruteforce",
      "j": 16,
      "token": " stdin with "
    },
    {
      "guesses": 6354,
      "guesses_log10": 3.8030472104911284,
      "l33t_variations": 1,
      "reversed": false,
      "rank": 6354,
      "uppercase_variations": 1,
      "dictionary_name": "english_wikipedia",
      "matched_word": "trailing",
      "base_guesses": 6354,
      "i": 17,
      "pattern": "dictionary",
      "j": 24,
      "l33t": false,
      "token": "trailing"
    },
    {
      "guesses": 11,
      "guesses_log10": 1.041392685158225,
      "i": 25,
      "pattern": "bruteforce",
      "j": 25,
      "token": " "
    },
    {
      "guesses": 2619,
      "guesses_log10": 3.4181354984252317,
      "l33t_variations": 1,
      "reversed": false,
      "rank": 2619,
      "uppercase_variations": 1,
      "dictionary_name": "english_wikipedia",
      "matched_word": "spaces",
      "base_guesses": 2619,
      "i": 26,
      "pattern": "dictionary",
      "j": 31,
      "l33t": false,
      "token": "spaces"
    },
    {
      "repeat_count": 4,
      "token": "    ",
      "base_token": " ",
      "guesses": 50,
      "base_guesses": "12",
      "guesses_log10": 1.6989700043360185,
      "base_matches": [
        {
          "guesses": 11,
          "guesses_log10": 1.041392685158225,
          "i": 0,
          "pattern": "bruteforce",
          "j": 0,
          "token": " "
        }
      ],
      "i": 32,
      "pattern": "repeat",
      "j": 35
    }
  ],
  "crack_times_display": {
    "online_throttling_100_per_hour": "centuries",
    "online_no_throttling_10_per_second": "centuries",
    "offline_fast_hashing_1e10_per_second": "centuries",
    "offline_slow_hashing_1e4_per_second": "centuries"
  },
  "score": 4,
  "password": "using stdin with trailing spaces    ",
  "calc_time": "0:00:00.025936"
}
```

### CODE REVIEW

**Comment by whwright** [comment]
I thought `read()` would be better than `readline()` for files and such. I have tested all the cases again.

**Comment by whwright** [comment]
Triggering a new CI build...

**Comment by whwright** [comment]
I'm not sure if my latest change is the cause of the failure or if it is a fluke, since it's running out of time. I will play around with the tests for 2.7 locally and see if I can get a better read on what is happening.

**Comment by dwolfhub** [comment]
Hey @whwright 

The 2.7 timeouts are a known issue. Is this PR ready for review?

**Comment by dwolfhub** [comment]
Thanks!

**Pull request merged**
